### PR TITLE
Add narration about crops ripe level and farmland wet state. Refactor block narration methods. close #44

### LINKED ISSUE #44: Report if crops are harvestable in ReadCrosshair
Things that can be planted and have grow stages. Including wheat, carrot, potato, beetroot, nether wart, cocoa bean, pitcher crop (as TODO until upgrade to 1.20). 

Also the [moisture state](https://minecraft.fandom.com/wiki/Farmland#Block%20states) of the farmland `blockState.get(FarmlandBlock.MOISTURE) == 7`.

### PR DESCRIPTION
**Pull request by boholder**
With https://github.com/khanshoaib3/minecraft-access-i18n/pull/6

### CODE REVIEW

**Comment by boholder** [comment]
Guess the `lang` submodule's version shouldn't be committed to GitHub?

**Comment by boholder** [comment]
And... I thought refactoring would simplify the code, but it doesn't seem to. Maybe it's the old saying "Complexity can't be reduced, it can only be moved from one place to another".

**Review by khanshoaib3 — APPROVED** [review]

**Comment by khanshoaib3** [comment]
> Guess the `lang` submodule's version shouldn't be committed to GitHub?

Sorry, what do you mean?

**Comment by boholder** [comment]
> Sorry, what do you mean?

The versions of git submodules are also a version controlled thing in parent project.
For example, I changed version of `lang` in this request to somewhere not on the main branch of `lang`.

But after you merge that lang request into lang main branch, the version of lang in this minecraft-access project should be changed to that merge commit.

**Pull request merged**
