### PR TITLE
Add speak harvest of fishing feature, to be clear it will report what your picked up when you're holding a fishing rod. 

### LINKED ISSUE #48: Speak the harvest of finishing
Feature request from Discord user lexi/scarlet#7459

implementation idea: mixin somewhere, if holding fish rod, speak the item.
like this one: https://github.com/FabricMC/fabric/issues/1130

### PR DESCRIPTION
**Pull request by boholder**
close #48

### CODE REVIEW

**Comment by khanshoaib3** [comment]
By looking at the code, I think that it will also speak the item name if we pick up items laying on the ground while holding the fishing rod. I;m not sure though.
Does that happen?

**Comment by boholder** [comment]
> By looking at the code, I think that it will also speak the item name if we pick up items laying on the ground while holding the fishing rod. I;m not sure though. Does that happen?

Yep, that's because the item entity is spawned at the position of the fishing bobber and flies to the player, normally the item will be picked up by the player, same as picking up items on the ground.
I can't find a way to detect "if the player is finishing", because at the time of player picks up item, the state of the player is just a player holding a fishing rod.

**Comment by khanshoaib3** [comment]
Thought so, it's fine for now I guess. Something is better than nothing.
I think we should add a config to make it toggleable.

**Review by khanshoaib3 — APPROVED** [review]

**Comment by boholder** [comment]
> I think we should add a config to make it toggleable.

Mm-hmm, I think so, I'll make one.

**Pull request merged**
