### PR TITLE
Reset previousQuery after every 5000ms

### PR DESCRIPTION
**Pull request by boholder**
Solve a related [TODO](https://github.com/khanshoaib3/minecraft-access/blob/b6702826583a9580dd9b57da88a68fe1891f5990/common/src/main/java/com/github/khanshoaib3/minecraft_access/features/ReadCrosshair.java#L54).

BTW, there are some `toSpeak` variables in `ReadCrosshair.class` that marked as *unused*, is that normal?

### CODE REVIEW

**Comment by khanshoaib3** [comment]
The `toSpeak` and `currentQuery` have different values, `currentQuery` is checked to not speak the same block repeatedly but two blocks can have same name, and should be spoken if the focus is changed. That's why currentQuery is used for checking but `toSpeak` is actually the one to be spoken. Maybe have the `speakIfFresh()` also accept `toSpeak` as parameter and use that in `speakWithNarrator()`.

**Comment by boholder** [comment]
This modification is quite... noisy (for me), the narrator keep reporting about the block you're pointing at every five seconds.
So I make the interval as a config.

**Comment by boholder** [comment]
BTW... Has your development environment's narrator ever failed? 
After a restart of debug mode, my narrator (Windows build-in narrator, not the tolk) stopped talking, even with the corresponding settings turned on. 
I'm not sure what happened or how to fix it.

**Comment by khanshoaib3** [comment]
I mainly use linux so I don't know and I haven't faced anything similar to that on linux, what happens when you refresh the screen reader after it happens?

**Review by khanshoaib3 — APPROVED** [review]

**Comment by boholder** [comment]
> what happens when you refresh the screen reader after it happens?

I... can't find a way to refresh the Windows build-in narrator, but things won't be solved even I reboot the computer. Thanks for your information, I'll try to find a way to refresh the narrator or just install the tolk...

**Comment by khanshoaib3** [comment]
I don't think we can refresh the default narrator, I thought you were using tolk.
Maybe the narrator gets disabled, try control + b to change the narrator's mode.

**Comment by boholder** [comment]
> I don't think we can refresh the default narrator, I thought you were using tolk.

I found the reason: [Merge pull request #29 from khanshoaib3/auto-installer](https://github.com/khanshoaib3/minecraft-access/commit/b6702826583a9580dd9b57da88a68fe1891f5990#diff-9cefaa1d613cc32c11bda90d860105294ae477e5b5b19d1c3b983ae87d76205b)
It seems that tolk binaries hijack the narrator-invokes...... After revert the commits, Windows narrator works again. (I'll keep them inside stash and would not commit the revert.) 👌

**Comment by khanshoaib3** [comment]
Yeah, the mod auto installs the tolk library as it supports NVDA, JAWS, the windows narrator and others.

**Comment by khanshoaib3** [comment]
This will probably be fixed when #3 is implemented.

**Pull request merged**
