### PR TITLE
Updates for 1.20.6

### PR DESCRIPTION
**Pull request by boholder**
[//]: # (The changelog will be added into CHANGELOG.md file automatically by fast-forward workflow.)

[//]: # (Please delete unrelevant changelog sections.)

### New Features

- Speak variant of dog, cat, axolotl
- Speak animals and monsters currently wearing equipment

### Bug Fixes

- Fix broken logic after upgrading to 1.20.6

### Translation Changes

- New field: entity wearing equipment format
- New field: animal variant format
- New field: variant of dog, cat, axolotl

### Development Chores

- New `NamedFormatter` class with modifications to `I18NMixin`, for easier I18N translation

### CODE REVIEW

**Comment by khanshoaib3** [comment]
\[Fast Forward CI\] 1.20.6 merged into 1.20... Copied the changelogs from pull request body to doc/CHANGELOG.md... Pushed the changes to origin.

**Comment by boholder** [comment]
@khanshoaib3 Maybe you can add the branch protection rule back?

**Comment by khanshoaib3** [comment]
> @khanshoaib3 Maybe you can add the branch protection rule back?

But that might still prevent the workflow to push the commits because essentially with that rule all the commits require a PR including the auto changelog commit.

**Comment by boholder** [comment]
Ok... make sense.

**Pull request merged**
