### PR TITLE
Mod Docs Overhaul

### PR DESCRIPTION
**Pull request by BrailleBennett**
This PR aims to rework the docs system. Starting with SETUP_ON_WINDOWS.md and expanding to cover most, if not all, existing documentation to make it more readable, organized, and easier for new players to understand. I also want to add a comprehensive guide for SETUP_AS_MODPACK, as currently the [Visually Impaired Access](https://modrinth.com/modpack/vi-access) mod pack has no instalation or updating documentation.

### CODE REVIEW

**Comment by BrailleBennett** [comment]
I intentionally removed the supported  mod versions file from the docs, as it is noted individually on each release.

**Comment by boholder** [comment]
> I intentionally removed the supported  mod versions file from the docs, as it is noted individually on each release.

Please add it back since the release info is generated from that doc.

**Comment by boholder** [comment]
BTW, can you rebase your branch onto branch 1.21 so we can keep a straight git commit tree?

**Review by boholder — APPROVED** [review]

**Comment by khanshoaib3** [comment]
\[Fast Forward CI\] PR cannot be merged in. Check the Actions tab for details.

**Comment by khanshoaib3** [comment]
\[Fast Forward CI\] PR cannot be merged in. Check the Actions tab for details.

**Comment by khanshoaib3** [comment]
\[Fast Forward CI\] PR cannot be merged in. Check the Actions tab for details.

**Pull request merged**
